name: Continue + OpenRouter
version: 0.0.1
schema: v1
models:
  - name: Qwen3 Coder Next
    provider: openrouter
    model: qwen/qwen3-coder-next
    apiKey: ""
    roles:
      - chat
      - edit
      - apply
  - name: Qwen3 Coder Next (autocomplete)
    provider: openrouter
    model: qwen/qwen3-coder-next
    apiKey: ""
    roles:
      - autocomplete
